DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS users;

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS users (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS messages (
    id SERIAL PRIMARY KEY,
    message VARCHAR NOT NULL,
    sender VARCHAR NOT NULL,
    user_id UUID REFERENCES users(id) ON DELETE CASCADE
);